### ISSUE TITLE
Styling parameters?

### ISSUE THREAD

**Issue by nuclearsecrecy** [protomaps/protomaps-leaflet#118]
Is there an even somewhat comprehensive list of what styling parameters there are for maps? I am trying to adapt TileJSON spec to JS spec and am having to go about it almost totally randomly for anything that is not covered by the very bare-boned examples. E.g., when trying to figure out how to make labels uppercase, I by chance stumbled across `textTransform`, and found it was only present in the attribute test file? 

I don't really understand how `label_props` works, for example, and it also doesn't really show up in the source exempt for test files.

I definitely don't understand how `json_style` works — even just one example would be useful — but I understand you are planning to deprecate it anyway, so I am not investing much time in that (even though it would be easiest — the main "use case" for this library, as I see it, is as a fallback for old browsers that do not support WebGL mapping libraries, and it is really a pain to have to re-do the stylesheet in the JS code when I already have it working in the JSON code, but I'm willing to do it if I can figure out how to do it)...

Thanks for your work on this — not trying to be a nag, just trying to see if there is an obvious place to look so I am not just flailing in the dark through trial-and-error to get a sense of how I am supposed to be doing this. The examples are too simplistic for a real application...

**Comment by bdon** [comment]
@nuclearsecrecy no, that doesn't exist right now.

I don't think this library is that useful as a fallback for another renderer like MapLibre. What are the browsers that do not support WebGL? From my understanding MapLibre has pretty good coverage for modern browsers, and if there are performance issues displaying raster tiles from osm.org or another free raster tile source could be an acceptable fallback solution. Using `protomaps-leaflet` as a fallback requires changing your application to use the Leaflet API and also can be laggy on slower devices.

**Comment by bdon** [comment]
Closing this issue because the `json_style` parts of the library have been removed. 

The only way now is to write Rules with Symbolizers, and those options are in the source code like here: https://github.com/protomaps/protomaps-leaflet/blob/main/src/symbolizer.ts#L74

But in general for highly custom use cases it's recommended to use MapLibre GL - this library exists mainly to support existing Leaflet applications that want to use PMTiles. You can see more in the CHANGELOG for the upcoming 2.0 release: https://github.com/protomaps/protomaps-leaflet/blob/main/CHANGELOG.md

It isn't useful as a fallback to MapLibre because its drawing routines are more CPU-demanding than MapLibre's - for a fallback, raster tiles are better.
