### ISSUE TITLE
is `queryFeatures` deprecated?

### ISSUE THREAD

**Issue by csbrown** [protomaps/protomaps-leaflet#134]
I would like to use some functionality related to retrieving polygons/features based on user interaction.  One of the [examples](https://github.com/protomaps/protomaps-leaflet/blob/main/examples/multi_language.html) calls a method `queryFeatures` that seems to accomplish more-or-less what I need.  However, I no longer see that method in the codebase, even though I have access to it through the module I installed with npm.  It seems that the module I have installed is v1.24

Is this querying feature deprecated?  If so, is there a recommended replacement for this workflow?

**Comment by bdon** [comment]
Yes, use MapLibre instead, because its internal design already supports user interaction out of the box.

**Comment by csbrown** [comment]
That's unfortunate.  Do you have recommendations on how to translate points from the internal coordinate system to lat/long?  I can roll my own `queryFeatures` with a kdtree.

**Comment by bdon** [comment]
I don't have any recommendations beyond how queryFeatures worked before, which is still in the Git history. The method used does not properly account for the difference between features in the tiles and features rendered by the style, does not persist properly across zoom interactions, and also doesn't work correctly when overzooming, which is why I recommend using MapLibre for anything involving dynamic interaction. It's not a good use of maintenance time to reproduce all those features when MapLibre already does them perfectly.
